#!/usr/bin/env python3
"""Export untrusted integer data and head-path witnesses for Lean to check.

Run from any directory. With --check, fail if the checked-in Lean file is stale.
The exporter proves nothing: Lean reconstructs transitions independently and
checks all assertions about the emitted data in its kernel.
"""
from __future__ import annotations

import argparse
from collections import deque
import json
from pathlib import Path

from verify_five import transition

ROOT = Path(__file__).resolve().parents[1]
START = ((0, 1), (2, 3, 4))


def lean_list(xs):
    return "[" + ", ".join(str(x).lower() for x in xs) + "]"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads((ROOT / "data/stationary_certificate.json").read_text())
    rows = [(tuple(map(tuple, row["state"])), row["weight"]) for row in data["states"]]
    graph = {s: [(transition(s, side, 0, 2), bool(side))
                 for side in (0, 1) if s[side]] for s, _ in rows}
    reverse = {s: [] for s in graph}
    for s, edges in graph.items():
        for t, side in edges:
            reverse[t].append((s, side))

    def paths(edges, backwards):
        found = {START: []}
        pending = deque([START])
        while pending:
            s = pending.popleft()
            for t, side in edges[s]:
                if t not in found:
                    found[t] = ([side] + found[s]) if backwards else (found[s] + [side])
                    pending.append(t)
        if len(found) != len(rows):
            raise ValueError("head graph is not strongly connected")
        return found

    forward, backward = paths(graph, False), paths(reverse, True)
    lines = [
        "import OddCycle.Model", "",
        "/-! Generated by code/export_lean_certificate.py. These are data, not axioms.",
        "Every weight and path is checked against the Lean model in FiveJob.lean. -/",
        "", "namespace OddCycle.FiveJob", "",
        "structure Witness where", "  state : State", "  weight : Nat",
        "  fromRoot : List Bool", "  toRoot : List Bool", "",
        "def witnesses : List Witness := [",
    ]
    for i, (s, weight) in enumerate(rows):
        comma = "," if i + 1 < len(rows) else ""
        lines.append(f"  ⟨({lean_list(s[0])}, {lean_list(s[1])}), {weight},")
        lines.append(f"    {lean_list(forward[s])}, {lean_list(backward[s])}⟩{comma}")
    lines += ["]", "", "end OddCycle.FiveJob", ""]
    output = ROOT / "OddCycle/Certificate.lean"
    text = "\n".join(lines)
    if args.check:
        if output.read_text() != text:
            raise SystemExit("Lean certificate is stale; run code/export_lean_certificate.py")
        print("PASS: Lean certificate matches the source data and deterministic paths.")
    else:
        output.write_text(text)
        print(f"Wrote {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
