#!/usr/bin/env python3
"""Exhaustive small-graph screen with a self-contained coverage check.

Verifies that the stored 61 graphs cover all non-isomorphic simple bipartite
graphs on 1..6 vertices. Coverage is regenerated by vertex addition and exact
degree-partitioned canonical labeling. Four further w=2 graphs are explicit.
Every queue configuration is then tested for reachability of height <= w under
head-only and all-position completions. Python 3.10+, standard library only.
"""
from __future__ import annotations
import json
import sys
from itertools import permutations, product
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def adjacency(n, edges):
    adj = [set() for _ in range(n)]
    for a, b in edges:
        require(0 <= a < b < n, 'invalid simple graph edge')
        adj[a].add(b); adj[b].add(a)
    return adj


def bipartite(n, edges):
    adj = adjacency(n, edges)
    color = {}
    for start in range(n):
        if start in color:
            continue
        color[start] = 0
        todo = [start]
        while todo:
            u = todo.pop()
            for v in adj[u]:
                if v not in color:
                    color[v] = 1 - color[u]; todo.append(v)
                elif color[v] == color[u]:
                    return False
    return True


def canonical(n, edges):
    adj = adjacency(n, edges)
    classes = {}
    for v in range(n):
        classes.setdefault(len(adj[v]), []).append(v)
    blocks = [classes[d] for d in sorted(classes)]
    candidates = product(*(permutations(b) for b in blocks))
    best = None
    for blocks_in_order in candidates:
        labels = [v for block in blocks_in_order for v in block]
        code = tuple(int(labels[j] in adj[labels[i]])
                     for i in range(n) for j in range(i + 1, n))
        if best is None or code < best:
            best = code
    return best if best is not None else ()


def decode(n, code):
    return [(i, j) for bit, (i, j) in zip(code,
            ((i, j) for i in range(n) for j in range(i + 1, n))) if bit]


def verify_coverage(records):
    previous = {()}
    counts = {}
    for n in range(1, 7):
        generated = set()
        for old in previous:
            base = decode(n - 1, old)
            for mask in range(1 << (n - 1)):
                edges = base + [(i, n - 1) for i in range(n - 1) if mask >> i & 1]
                if bipartite(n, edges):
                    generated.add(canonical(n, edges))
        supplied = [r for r in records if r['w'] == 1 and r['n'] == n]
        require(all(bipartite(n, r['edges']) for r in supplied), 'nonbipartite screen graph')
        supplied_codes = {canonical(n, r['edges']) for r in supplied}
        require(len(supplied_codes) == len(supplied), 'duplicate isomorphism class')
        require(supplied_codes == generated, 'stored screen does not cover all bipartite graphs')
        counts[n] = len(generated)
        previous = generated
    require(sum(counts.values()) == 61, 'wrong bipartite graph count')
    return counts


def check_graph(record):
    n, w = record['n'], record['w']
    adj = adjacency(n, record['edges'])
    states = [(p[:k], p[k:]) for p in permutations(range(n)) for k in range(n + 1)]
    index = {s: i for i, s in enumerate(states)}
    def height(s):
        depth = {}
        for v in s[0] + s[1][::-1]:
            depth[v] = max((depth[u] + 1 for u in adj[v] if u in depth), default=0)
        return max(depth.values(), default=0)
    good = {i for i, s in enumerate(states) if height(s) <= w}
    heads, allpos = [[] for _ in states], [[] for _ in states]
    events = 0
    for i, s in enumerate(states):
        for side in (0, 1):
            for p in range(len(s[side])):
                rest = list(s[side]); job = rest.pop(p); used = 0
                for j in range(p, len(rest)):
                    if rest[j] in adj[job]:
                        job, rest[j] = rest[j], job; used += 1
                        if used == w:
                            break
                t = list(s); t[side] = tuple(rest); t[1-side] += (job,)
                k = index[tuple(t)]
                require(i not in good or k in good, 'short region unexpectedly not closed')
                allpos[k].append(i)
                if p == 0:
                    heads[k].append(i)
                events += 1
    def backwards(reverse):
        seen, todo = set(good), list(good)
        while todo:
            for j in reverse[todo.pop()]:
                if j not in seen:
                    seen.add(j); todo.append(j)
        return len(states) - len(seen)
    head_missing, all_missing = backwards(heads), backwards(allpos)
    require(head_missing == all_missing == 0, 'a state cannot reach a short orientation')
    return dict(name=record['name'], n=n, w=w, states=len(states),
                all_position_events=events, good_states=len(good),
                head_states_unable_to_reach_good=head_missing,
                all_position_states_unable_to_reach_good=all_missing)


def run():
    graphs = json.loads((ROOT/'data/screen_graphs.json').read_text())
    coverage = verify_coverage(graphs)
    require(len(graphs) == 65 and sum(r['w'] == 2 for r in graphs) == 4,
            'wrong number of screen graphs')
    results = [check_graph(r) for r in graphs]
    return {'status': 'PASS', 'graphs': len(results), 'bipartite_w1_graphs': 61,
            'bipartite_isomorphism_classes_by_vertices': coverage,
            'coverage_rebuilt_without_external_libraries': True,
            'total_states': sum(r['states'] for r in results),
            'all_position_events': sum(r['all_position_events'] for r in results),
            'all_head_reachability_checks_pass': True,
            'all_position_reachability_checks_pass': True, 'cases': results}


if __name__ == '__main__':
    try:
        print(json.dumps(run(), indent=2))
    except (RuntimeError, OSError, ValueError) as exc:
        print(f'FAIL: {exc}', file=sys.stderr)
        raise SystemExit(1)
