import OddCycle.CycleClassification

#print axioms OddCycle.ReachabilityQuotient.reach_iff
#print axioms OddCycle.ReachabilityQuotient.terminal_iff
#print axioms OddCycle.CycleState.orientation_reachable_iff
#print axioms OddCycle.CycleState.terminal_orientation_iff
#print axioms OddCycle.CircularRun.terminal_iff
#print axioms OddCycle.CircularRun.exceptional_iff_one_long
#print axioms OddCycle.CircularRun.exceptional_cycle_length
#print axioms OddCycle.ExceptionalCycle.communication
#print axioms OddCycle.ExceptionalCycle.parameter_count
#print axioms OddCycle.CircularWord.encode_linearRuns
#print axioms OddCycle.CircularWord.circularRuns_sum
#print axioms OddCycle.CircularWord.circularRuns_positive
#print axioms OddCycle.CircularWord.circularRuns_even
#print axioms OddCycle.orientation_nonconstant
#print axioms OddCycle.cycleRuns_sum
#print axioms OddCycle.cycleRuns_even
#print axioms OddCycle.exceptionalRuns_cycle_length
#print axioms OddCycle.even_cycle_not_exceptional
#print axioms OddCycle.carry_eq_unlimited_of_paths
#print axioms OddCycle.transition_short_orientation
#print axioms OddCycle.height_eq_of_orientation_eq
#print axioms OddCycle.short_reachable_iff
#print axioms OddCycle.short_terminal
#print axioms OddCycle.scanFrontier_result
#print axioms OddCycle.scanFrontier_edgeEquiv
#print axioms OddCycle.scanFrontier_chain_untouched_sublist
#print axioms OddCycle.scanFrontier_exhausted
#print axioms OddCycle.scanFrontier_long_path
#print axioms OddCycle.scanFrontier_unique_cycle_neighbor
#print axioms OddCycle.complete_cycle_changed_path
#print axioms OddCycle.first_transition_changed_path
#print axioms OddCycle.transition_changed_path
#print axioms OddCycle.large_budget_preserves_orientation
#print axioms OddCycle.FiniteMarkov.terminal_returnBy_tendsto_one
#print axioms OddCycle.CycleState.terminal_returnBy_tendsto_one
#print axioms OddCycle.CycleState.short_returnBy_tendsto_one
#print axioms OddCycle.scanFrontier_follows_cycle
#print axioms OddCycle.cycle_path_realize_flip
#print axioms OddCycle.orientationStep_iff_pathFlip
#print axioms OddCycle.cycle_path_is_arc
#print axioms OddCycle.CircularWord.linearRuns_encode
#print axioms OddCycle.CircularWord.circularRuns_isRotated
#print axioms OddCycle.CircularWord.short_iff_no_long_circularBlock
#print axioms OddCycle.shortRuns_iff_height
#print axioms OddCycle.shortRuns_reachable_iff
#print axioms OddCycle.shortRuns_terminal
#print axioms OddCycle.CircularWord.LinearFlip.run_reachable
#print axioms OddCycle.CircularWord.augmentedReach_iff_runs
#print axioms OddCycle.CircularWord.augmented_terminal_iff
#print axioms OddCycle.ReachabilityQuotient.terminal_augment_iff
#print axioms OddCycle.BinaryCycle.terminal_iff
#print axioms OddCycle.orientation_surjective
#print axioms OddCycle.orientationStep_iff_circularFlip
#print axioms OddCycle.CycleState.reachable_iff_binary
#print axioms OddCycle.CycleState.terminal_iff_runs
#print axioms OddCycle.CycleState.even_terminal_short
#print axioms OddCycle.CycleState.classified_returnBy_tendsto_one
#print axioms OddCycle.exceptionalRuns_transition
#print axioms OddCycle.exists_tall_terminal_iff
#print axioms OddCycle.exceptionalParameter_communication
#print axioms OddCycle.exceptionalParameter_covers
#print axioms OddCycle.exceptionalRuns_communicate
#print axioms OddCycle.exceptionalParameter_injective
#print axioms OddCycle.exceptional_orientation_count
#print axioms OddCycle.FiniteMarkov.returnBy_tendsto_one_iff_terminal
#print axioms OddCycle.FiniteMarkov.avoid_terminal_tendsto_zero
#print axioms OddCycle.CycleState.recurrent_iff_runs
#print axioms OddCycle.CycleState.transient_iff_runs
#print axioms OddCycle.CycleState.classified_avoid_tendsto_zero
#print axioms OddCycle.CycleState.short_avoid_tendsto_zero
#print axioms OddCycle.CycleState.exceptional_recurrent_state
#print axioms OddCycle.OICapacity.unlimited_partial_balance
#print axioms OddCycle.unlimitedOccurrences_complete
#print axioms OddCycle.oiBalance_eq_positionGenerator
#print axioms OddCycle.unlimited_oi_stationary
#print axioms OddCycle.nonexceptional_recurrent_oi_stationary
#print axioms OddCycle.even_recurrent_oi_stationary
#print axioms OddCycle.short_class_normalized_oi

#print axioms OddCycle.closed_class_classification
#print axioms OddCycle.balanced_is_exceptional
#print axioms OddCycle.ClosedClass.safe_normalized_oi
#print axioms OddCycle.PositivePositionAllocation.kernel_pos_iff
#print axioms OddCycle.PositivePositionAllocation.recurrent_iff_runs
#print axioms OddCycle.PositivePositionAllocation.classified_absorption
#print axioms OddCycle.PositivePositionAllocation.short_absorption
#print axioms OddCycle.unit_target_orientation
#print axioms OddCycle.unit_gain_exceptional
#print axioms OddCycle.unit_gained_predecessors
#print axioms OddCycle.unit_lost_predecessors
#print axioms OddCycle.unit_exceptional_residual
#print axioms OddCycle.unit_exceptional_not_stationary
#print axioms OddCycle.oiBalance_additive
#print axioms OddCycle.cycle_canonical_sharpness
#print axioms OddCycle.NineJobCycle.residual

#print axioms OddCycle.cycle_normalized_canonical_sharpness

#print axioms OddCycle.FiniteMarkov.pathMeasureFrom_step
#print axioms OddCycle.FiniteMarkov.pathMeasureFrom_avoid
#print axioms OddCycle.FiniteMarkov.pathMeasure_return_iff
#print axioms OddCycle.FiniteMarkov.pathMeasure_ae_steps
#print axioms OddCycle.ExponentialClock.law_map
#print axioms OddCycle.ExponentialClock.law_eval
#print axioms OddCycle.ExponentialClock.law_independent
#print axioms OddCycle.ExponentialClock.clock_diverges
#print axioms OddCycle.FiniteMarkov.eventTime_nonexplosive
#print axioms OddCycle.FiniteMarkov.timedState_measurable
#print axioms OddCycle.FiniteMarkov.timedState_between
#print axioms OddCycle.FiniteMarkov.first_completion_law
#print axioms OddCycle.FiniteMarkov.continuous_recurrence_iff
#print axioms OddCycle.FiniteMarkov.continuous_absorption
#print axioms OddCycle.FiniteMarkov.continuous_eventually_one_class
#print axioms OddCycle.PositivePositionAllocation.process_nonexplosive
#print axioms OddCycle.PositivePositionAllocation.completion_rate_identity
#print axioms OddCycle.PositivePositionAllocation.completion_law
#print axioms OddCycle.PositivePositionAllocation.continuous_recurrent_iff_runs
#print axioms OddCycle.PositivePositionAllocation.continuous_classified_absorption
#print axioms OddCycle.PositivePositionAllocation.continuous_short_absorption
#print axioms OddCycle.PositivePositionAllocation.continuous_eventually_classified
#print axioms OddCycle.PositivePositionAllocation.continuous_eventually_one_class
#print axioms OddCycle.CycleClassifier.ranks_get
#print axioms OddCycle.CycleClassifier.ranked_orientation
#print axioms OddCycle.CycleClassifier.runsWork_spec
#print axioms OddCycle.CycleClassifier.classify_correct
#print axioms OddCycle.CycleClassifier.classify_cost
#print axioms OddCycle.CycleClassifier.classify_terminal
#print axioms OddCycle.CycleClassifier.classify_continuous_recurrence
